### ISSUE TITLE
Screenshot please!

### ISSUE THREAD

**Issue by p0nce** [ZombineDev/Chess2RT#1]
It is always nice to have an image for a raytracer homepage. :)

**Comment by PetarKirov** [comment]
@p0nce Hey, thanks for the interest :)))
I still have a lot of work to do (refactoring, parallelism, shaders, loading custom 3d models), but I hope I'll have something to show a week or two from now.

**Comment by p0nce** [comment]
OK, let me know if `gfm:math` isn't fast enough in places. :)

**Comment by PetarKirov** [comment]
Yeah, I was thinking of using the raytracer for benchmarking, but it is currently quite inefficient.
 I use arrays of classes so I probably have pretty poor cache locality :smile: BTW the GC is not a problem because my `render` function is `@nogc` (and everything it calls) so it's almost allocation free, apart from a small array I need to dynamically malloc in one place.
When I get to optimizing, I'll be sure to carefully look at how `gfm:math` performs ;)

**Comment by p0nce** [comment]
`--combined` can help with cross-inlining.

**Comment by PetarKirov** [comment]
Thanks for the tip!

**Comment by p0nce** [comment]
Looks cool!

**Comment by PetarKirov** [comment]
Thanks! Due to lack of free time it's still far from where I want to go: EXR textures (WIP), custom 3D models (WIP), more light and camera types and (of course!) global illumination (WIP) ;)
